<template>
  <div class="assets-view">
    <h1>Game Assets: Dice</h1>
    <p>This page displays the dice images used in the game and their expected filenames.</p>
    <div v-if="isLoading" class="loading-message">Loading asset list...</div>
    <div v-else-if="diceAssets.length === 0" class="no-assets-message">
      No dice assets found or generated.
    </div>
    <div v-else class="assets-grid">
      <div v-for="asset in diceAssets" :key="asset.filename" class="asset-item">
        <div class="image-container">
          <img
            v-if="asset.url && !asset.error"
            :src="asset.url"
            :alt="asset.filename"
            @error="() => (asset.error = true)"
          />
          <span v-if="asset.error || !asset.url" class="fallback-text">[img]</span>
        </div>
        <p class="filename">{{ asset.filename || "N/A" }}</p>
        <p class="details">
          (Type: {{ asset.die.type
          }}{{ asset.die.value !== undefined ? ", Value: " + asset.die.value : "" }})
        </p>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref, onMounted } from "vue";
import { DICE_TYPES } from "@/stores/game"; // Assuming DICE_TYPES is exported from your game store
import { generateDieImageFilename, getDieImageUrl } from "@/utils/imageUtils"; // Adjust path if needed

const diceAssets = ref([]);
const isLoading = ref(true);

function generateAssetList() {
  const assets = [];
  const diceToDisplay = [
    { type: DICE_TYPES.NORMAL },
    { type: DICE_TYPES.REVERSE_RANDOM },
    { type: DICE_TYPES.D20 },
    // Add D20_REVERSE if you have it
    // { type: DICE_TYPES.D20_REVERSE }
  ];

  for (let i = 1; i <= 6; i++) {
    diceToDisplay.push({ type: DICE_TYPES.FIXED, value: i });
    diceToDisplay.push({ type: DICE_TYPES.REVERSE_FIXED, value: i });
  }
  // Add any other specific dice like fixed values greater than 6 if they exist.

  diceToDisplay.forEach((die) => {
    const filename = generateDieImageFilename(die); // die object directly
    if (filename) {
      const url = getDieImageUrl(filename);
      assets.push({
        filename,
        url,
        die, // Store original die info for display details
        error: false, // To track loading errors for individual images
      });
    } else {
      assets.push({
        filename: `Unknown for ${die.type}${die.value ? "_" + die.value : ""}`,
        url: null,
        die,
        error: true,
      });
    }
  });

  // Remove duplicates by filename if any were generated by mistake
  const uniqueAssets = [];
  const seenFilenames = new Set();
  for (const asset of assets) {
    if (asset.filename && !seenFilenames.has(asset.filename)) {
      uniqueAssets.push(asset);
      seenFilenames.add(asset.filename);
    } else if (!asset.filename) {
      // Keep items that failed to generate a filename for review
      uniqueAssets.push(asset);
    }
  }

  return uniqueAssets;
}

onMounted(() => {
  diceAssets.value = generateAssetList();
  isLoading.value = false;
});
</script>

<style scoped>
.assets-view {
  padding: 20px;
  font-family: "Segoe UI", Tahoma, Geneva, Verdana, sans-serif;
}
h1 {
  text-align: center;
  margin-bottom: 20px;
  color: #2c3e50;
}
.assets-grid {
  display: grid;
  grid-template-columns: repeat(auto-fill, minmax(150px, 1fr));
  gap: 20px;
}
.asset-item {
  border: 1px solid #ddd;
  border-radius: 8px;
  padding: 15px;
  text-align: center;
  background-color: #f9f9f9;
  box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
}
.image-container {
  width: 100px;
  height: 100px;
  margin: 0 auto 10px auto;
  display: flex;
  align-items: center;
  justify-content: center;
  border: 1px solid #eee;
  background-color: #fff;
}
.asset-item img {
  max-width: 100%;
  max-height: 100%;
  object-fit: contain;
}
.fallback-text {
  display: inline-block;
  width: 100%;
  height: 100%;
  line-height: 100px; /* Vertically center */
  text-align: center;
  font-size: 14px;
  color: #777;
  background-color: #f0f0f0;
}
.filename {
  font-weight: bold;
  margin-bottom: 5px;
  word-break: break-all;
  font-size: 0.9em;
}
.details {
  font-size: 0.8em;
  color: #555;
}
.loading-message,
.no-assets-message {
  text-align: center;
  font-size: 1.2em;
  color: #777;
  padding: 30px;
}
</style>
