name: Docker Build and Push

on:
  push:
    branches:
      - main

jobs:
  build-and-push-docker-image: # Renamed job for clarity
    name: Build and Push to Docker Hub
    runs-on: ubuntu-latest # Use the latest Ubuntu runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Updated to the latest major version

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3 # Updated to the latest major version

      - name: Login to Docker Hub
        uses: docker/login-action@v3 # Updated to the latest major version
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5 # Updated to the latest major version
        with:
          context: . # Use the current directory as the build context
          file: ./Dockerfile # Explicitly specify the Dockerfile location
          push: true # Actually push the image to Docker Hub
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/dice_or_die:latest
