name: Test and Lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  STORE_PATH: ~/.pnpm-store

jobs:
  test-and-lint:
    name: Run Tests and Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false

      - name: Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: |
          pnpm install --no-frozen-lockfile
          pnpm add -D jsdom @vue/test-utils @testing-library/vue @testing-library/jest-dom

      - name: Run lint check
        run: pnpm lint:ci

      - name: Run tests
        run: pnpm test:ci
